### ISSUE TITLE
ComandText object not set to instace of an object

### ISSUE THREAD

**Issue by KyleGobel** [ttakahari/AdoNetProfiler#5] opened 2018-03-21 21:10 UTC
Hi,

I'm not certain under which circumstances this happens, but this line here has the capability of not being initialized.

https://github.com/ttakahari/AdoNetProfiler/blob/master/src/AdoNetProfiler/AdoNetProfilerDbCommand.cs#L30

We get quite a few random errors where the stacktrace looks something like this:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AdoNetProfiler.AdoNetProfilerDbCommand.get_CommandText()
```

Sometimes it works, other times it errors..some race condition or something.

The latest one (stack trace i'm staring it, was triggered from ``OnReaderFinish()``) but i've seen it in other places

**Comment by ttakahari** [comment] 2018-03-22 00:52
@KyleGobel 

Thank you for reporting.

I want to know details to reproduce this issue.
Would you tell me following items?
* Which framework and version? (.NET Framework / .NET Core / etc...)
* Which RDB use? (SQL Server / MySQL / etc...)
* Use any ORM libraries? (EntitiyFramework / Dapper / etc...)
* Use asynchronous methods?
* Any common point?

Thank you.

**Comment by KyleGobel** [comment] 2018-03-22 13:59
- .NET Core (error has occured on both 2.0 and 1.x)
 - Postgres
 - Dapper
 - Yes everything is async

I've tried to reproduce the issue, unfortunately it's very hard as most of the time it works.  When debugging for example I can never get it to error.  I haven't looked a bunch into your profiler code tho to see where the ``WrappedConnection`` can be null though.

If there's anything I can provide to help out let me know.

**Comment by ttakahari** [comment] 2018-03-23 00:56
OK, I try to reproduce.
Before that, would you check to use async-methods with `await`?
If you use async-methods without `await` (This means 'fire and forget'.), errors may happen because `DbConnection` and/or `DbCommand` may be disposed while executing queries.

**Comment by KyleGobel** [comment] 2018-03-24 03:25
Everything is properly awaited.  

```
using (var db = await conn.OpenAsync()) 
{
    return await db.QueryAsync<Pet>("SELECT * FROM Pet");
}
```

This happens across all apps, this isn't just one thing.  Removing the profiler removes the issues.

**Comment by ttakahari** [comment] 2018-03-25 16:57
I try to reproduce with the under codes but such errors never happens.
```csharp
class Program
{
    static void Main(string[] args)
    {
        Parallel.For(0, 10000, new ParallelOptions { MaxDegreeOfParallelism = 1000 }, async i =>
        {
            using (var connection = new AdoNetProfilerDbConnection(
                new NpgsqlConnection(@"Server=localhost;Port=5432;User Id=postgres;Password=xxxx;Database=postgres"),
                new ConsoleProfiler()))
            {
                await connection.OpenAsync();

                await connection.QueryAsync<Test>(@"SELECT * FROM Test");
            }
        });

        Console.ReadLine();
    }
}
```
Are there remarkable differences form your codes?

**Comment by ttakahari** [comment] 2018-03-25 17:17
I reproduced the error with the following code.
```csharp
class Program
{
    static void Main(string[] args)
    {
        using (var connection = new AdoNetProfilerDbConnection(
            new NpgsqlConnection(@"Server=localhost;Port=15432;User Id=postgres;Password=xxxxx;Database=postgres"),
            new ConsoleProfiler()))
        {
            Parallel.For(0, 10000, new ParallelOptions { MaxDegreeOfParallelism = 1000 }, async i =>
            {
                await connection.OpenAsync();

                await connection.QueryAsync<Test>(@"SELECT * FROM Test");
            });
        }

        Console.ReadLine();
    }
}
```
And stack trace is following.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AdoNetProfiler.AdoNetProfilerDbCommand.get_CommandText()

Unhandled Exception:
Unhandled Exception:
Unhandled Exception:
Unhandled Exception:
Unhandled Exception: System.InvalidOperationException: Connection already open
   at Npgsql.NpgsqlConnection.CheckConnectionClosed()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at AdoNetProfiler.AdoNetProfilerDbConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.InvalidOperationException: Connection already open
   at Npgsql.NpgsqlConnection.CheckConnectionClosed()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at AdoNetProfiler.AdoNetProfilerDbConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Npgsql.NpgsqlOperationInProgressException: A command is already in progress: SELECT ns.nspname, a.typname, a.oid, a.typrelid, a.typbasetype,
CASE WHEN pg_proc.proname='array_recv' THEN 'a' ELSE a.typtype END AS type,
CASE
  WHEN pg_proc.proname='array_recv' THEN a.typelem
  WHEN a.typtype='r' THEN rngsubtype
  ELSE 0
END AS elemoid,
CASE
  WHEN pg_proc.proname IN ('array_recv','oidvectorrecv') THEN 3    /* Arrays last */
  WHEN a.typtype='r' THEN 2                                        /* Ranges before */
  WHEN a.typtype='d' THEN 1                                        /* Domains before */
  ELSE 0                                                           /* Base types first */
END AS ord
FROM pg_type AS a
JOIN pg_namespace AS ns ON (ns.oid = a.typnamespace)
JOIN pg_proc ON pg_proc.oid = a.typreceive
LEFT OUTER JOIN pg_type AS b ON (b.oid = a.typelem)
LEFT OUTER JOIN pg_range ON (pg_range.rngtypid = a.oid)
WHERE
  (
    a.typtype IN ('b', 'r', 'e', 'd') AND
    (b.typtype IS NULL OR b.typtype IN ('b', 'r', 'e', 'd'))  /* Either non-array or array of supported element type */
  ) OR
  (a.typname IN ('record', 'void') AND a.typtype = 'p')
ORDER BY ord
   at Npgsql.NpgsqlConnector.StartUserAction(ConnectorState newState, NpgsqlCommand command)
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Npgsql.TypeHandlerRegistry.<LoadBackendTypes>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.TypeHandlerRegistry.<Setup>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__145.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at AdoNetProfiler.AdoNetProfilerDbConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Npgsql.NpgsqlOperationInProgressException: A command is already in progress: SELECT ns.nspname, a.typname, a.oid, a.typrelid, a.typbasetype,
CASE WHEN pg_proc.proname='array_recv' THEN 'a' ELSE a.typtype END AS type,
CASE
  WHEN pg_proc.proname='array_recv' THEN a.typelem
  WHEN a.typtype='r' THEN rngsubtype
  ELSE 0
END AS elemoid,
CASE
  WHEN pg_proc.proname IN ('array_recv','oidvectorrecv') THEN 3    /* Arrays last */
  WHEN a.typtype='r' THEN 2                                        /* Ranges before */
  WHEN a.typtype='d' THEN 1                                        /* Domains before */
  ELSE 0                                                           /* Base types first */
END AS ord
FROM pg_type AS a
JOIN pg_namespace AS ns ON (ns.oid = a.typnamespace)
JOIN pg_proc ON pg_proc.oid = a.typreceive
LEFT OUTER JOIN pg_type AS b ON (b.oid = a.typelem)
LEFT OUTER JOIN pg_range ON (pg_range.rngtypid = a.oid)
WHERE
  (
    a.typtype IN ('b', 'r', 'e', 'd') AND
    (b.typtype IS NULL OR b.typtype IN ('b', 'r', 'e', 'd'))  /* Either non-array or array of supported element type */
  ) OR
  (a.typname IN ('record', 'void') AND a.typtype = 'p')
ORDER BY ord
   at Npgsql.NpgsqlConnector.StartUserAction(ConnectorState newState, NpgsqlCommand command)
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Npgsql.TypeHandlerRegistry.<LoadBackendTypes>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.TypeHandlerRegistry.<Setup>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__145.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at AdoNetProfiler.AdoNetProfilerDbConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()Npgsql.NpgsqlOperationInProgressException: A command is already in progress: SELECT ns.nspname, a.typname, a.oid, a.typrelid, a.typbasetype,
CASE WHEN pg_proc.proname='array_recv' THEN 'a' ELSE a.typtype END AS type,
CASE
  WHEN pg_proc.proname='array_recv' THEN a.typelem
  WHEN a.typtype='r' THEN rngsubtype
  ELSE 0
END AS elemoid,
CASE
  WHEN pg_proc.proname IN ('array_recv','oidvectorrecv') THEN 3    /* Arrays last */
  WHEN a.typtype='r' THEN 2                                        /* Ranges before */
  WHEN a.typtype='d' THEN 1                                        /* Domains before */
  ELSE 0                                                           /* Base types first */
END AS ord
FROM pg_type AS a
JOIN pg_namespace AS ns ON (ns.oid = a.typnamespace)
JOIN pg_proc ON pg_proc.oid = a.typreceive
LEFT OUTER JOIN pg_type AS b ON (b.oid = a.typelem)
LEFT OUTER JOIN pg_range ON (pg_range.rngtypid = a.oid)
WHERE
  (
    a.typtype IN ('b', 'r', 'e', 'd') AND
    (b.typtype IS NULL OR b.typtype IN ('b', 'r', 'e', 'd'))  /* Either non-array or array of supported element type */
  ) OR
  (a.typname IN ('record', 'void') AND a.typtype = 'p')
ORDER BY ord
   at Npgsql.NpgsqlConnector.StartUserAction(ConnectorState newState, NpgsqlCommand command)
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Npgsql.TypeHandlerRegistry.<LoadBackendTypes>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.TypeHandlerRegistry.<Setup>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__145.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at AdoNetProfiler.AdoNetProfilerDbConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
It may happen when a instance of `DbConnection` is used between multi-threads. Because `DbConnection` is not thread-safe, it must be instanced in each threads. Please check whether your codes use instances of `DbConnection` between multi-threads or not.

**Comment by ttakahari** [comment] 2018-03-28 03:40
@KyleGobel 
How about this matter?
If you don't use `DbConnection` among multi-threads, I keep to try reproducing.

**Comment by KyleGobel** [comment] 2018-03-30 14:07
Hmm, interesting, I will dig more into this when I get a chance.

I don't explicitly use multiple threads, but we do have an DbConnectionFactory that handles getting the various types of connections for us that I haven't looked at in a long time, i wonder if there's anything going on there.

Still curious though why this would happen when the NpgsqlConnection is wrapped in the AdoNetProfilerDbConnection, but not when using the regular NpgsqlConnection.

I'll post updates when I can

**Comment by ttakahari** [comment] 2018-04-02 01:13
Would you tell me what is DbConnectionFactory?
If it means `DbProviderFactories`, I think it cannot be used with .NET Core.
And please show me more details of stacktrace, if you can.

**Comment by KyleGobel** [comment] 2018-04-20 00:48
I don't know what DbProviderFactories means, our connection factory is home made.

Here's some relevant parts.

```cs
 // constructor
 public PostgresDbConnectionFactory(string connectionString, IAdoNetProfiler profiler = null)
 {
     _dbProfiler = profiler ?? new SqlProfiler();
     _defaultProvider =
        () => new AdoNetProfilerDbConnection(new NpgsqlConnection(connectionString),_dbProfiler);
 }

// main method used to open an async 'default' connection
 public async Task<IDbConnection> OpenConnectionAsync(bool profilerEnabled = true, CancellationToken cancel = default(CancellationToken))
 {
     var connection = _defaultProvider();
     if (!profilerEnabled && connection is AdoNetProfilerDbConnection)
     {
         connection = (connection as AdoNetProfilerDbConnection).WrappedConnection;
     }
     await ((DbConnection) connection).OpenAsync(cancel).ConfigureAwait(false);
     return connection;
 }
```

Here is a recent stacktrace:

```
[04:14:46 ERR] Unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at AdoNetProfiler.AdoNetProfilerDbCommand.get_CommandText()
   at MicroK.Core.SqlProfiler.OnReaderFinish(DbDataReader reader, Int32 records)
   at AdoNetProfiler.AdoNetProfilerDbDataReader.Dispose(Boolean disposing)
   at System.Data.Common.DbDataReader.Dispose()
   at Dapper.SqlMapper.<QueryImpl>d__136`1.<>m__Finally1() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1127
   at Dapper.SqlMapper.<QueryImpl>d__136`1.System.IDisposable.Dispose()
   at Dapper.SqlMapper.<QueryImpl>d__136`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1132
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 723
```

**Comment by KyleGobel** [comment] 2018-04-20 00:55
The relevant lines from the profiler

```cs
 public void OnReaderFinish(DbDataReader reader, int records)
 {
       _stopwatch.Stop();
   
       // this line fails...sometimes 
       if (_command?.CommandText != null)
       {
            // do some logging
       }
 }
```

**Comment by ttakahari** [comment] 2018-05-03 16:51
@KyleGobel 
I found why the error occurs. An instance of `IAdoNetProfiler` is not thread-safe.
You use an instance of `IAdoNetProfiler` among each connections but you should not.
I recommend to create an instance of `IAdoNetProfiler` for an instance of `AdoNetProfilerDbConnection` or use it wrapped by `ThreadLocal`.
[MiniProfiler](https://github.com/MiniProfiler/dotnet) behaves as AdoNetProfiler.

**Comment by ttakahari** [comment] 2018-05-19 10:32
I close this issue because I could reproduce with your code and it was not a bug.
If you don't use an instance of `IAdoNetProfiler` among some connections and the error occurs again, please create another new issue.

**Closed as completed by ttakahari** 2018-05-19 10:32 UTC

**Comment by KyleGobel** [comment] 2018-05-19 14:22
Thanks, I didn't realize I was re-using the same `IAdoNetProfiler`, re-enabled in some spots creating a new instance per connection and haven't seen any issues.  

Sorry!
